services:
  - type: web
    name: make-it-out-the-group-chat-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
